version: 2
updates:
  - package-ecosystem: "npm"
    directory: "src"
    schedule:
      interval: "daily"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "test"
    schedule:
      interval: "daily"
    versioning-strategy: increase